# Generated by Django 6.0.5 on 2026-05-26 19:07

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmissionFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("DIESEL", "Diesel"),
                            ("PETROL", "Petrol"),
                            ("NATGAS", "Natural Gas"),
                            ("LPG", "LPG"),
                            ("FUEL_OIL", "Fuel Oil"),
                            ("COAL", "Coal"),
                            ("KEROSENE", "Kerosene"),
                            ("ELECTRICITY", "Electricity"),
                            ("FLIGHT_ECONOMY", "Flight Economy"),
                            ("FLIGHT_PREMIUM", "Flight Premium Economy"),
                            ("FLIGHT_BUSINESS", "Flight Business"),
                            ("FLIGHT_FIRST", "Flight First"),
                            ("HOTEL", "Hotel"),
                            ("CAR", "Car (spend-based)"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                (
                    "unit",
                    models.CharField(
                        help_text="L, M3, KG, KWH, KM, NIGHT, INR", max_length=10
                    ),
                ),
                (
                    "factor_kgco2e",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="Emission factor in kgCO2e per unit",
                        max_digits=10,
                    ),
                ),
                (
                    "source",
                    models.CharField(help_text="DEFRA_2024, CEA_2024", max_length=50),
                ),
                ("year", models.IntegerField(default=2024)),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "emission_factors",
                "ordering": ["fuel_type"],
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "organizations",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Facility",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facilities",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "facilities",
                "db_table": "facilities",
                "ordering": ["name"],
                "unique_together": {("org", "name")},
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("analyst", "Analyst"), ("admin", "Admin")],
                        default="analyst",
                        max_length=20,
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "users",
                "ordering": ["username"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="ClientMaterialGroupMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "matkl_code",
                    models.CharField(
                        help_text="SAP Material Group code", max_length=50
                    ),
                ),
                (
                    "fuel_type",
                    models.CharField(
                        choices=[
                            ("DIESEL", "Diesel"),
                            ("PETROL", "Petrol"),
                            ("NATGAS", "Natural Gas"),
                            ("LPG", "LPG"),
                            ("FUEL_OIL", "Fuel Oil"),
                            ("COAL", "Coal"),
                            ("KEROSENE", "Kerosene"),
                            ("ELECTRICITY", "Electricity"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "scope",
                    models.IntegerField(choices=[(1, "Scope 1"), (2, "Scope 2")]),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="material_mappings",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "client_material_group_mappings",
                "ordering": ["matkl_code"],
                "unique_together": {("org", "matkl_code")},
            },
        ),
        migrations.CreateModel(
            name="PlantLookup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[("SAP", "SAP"), ("UTILITY", "Utility")], max_length=20
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="SAP WERKS code or utility meter number",
                        max_length=100,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_codes",
                        to="core.facility",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plant_lookups",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "plant_lookups",
                "ordering": ["source_type", "code"],
                "unique_together": {("org", "source_type", "code")},
            },
        ),
        migrations.CreateModel(
            name="ReportingPeriodLock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "period_month",
                    models.DateField(
                        help_text="First day of the month (e.g., 2024-01-01)"
                    ),
                ),
                ("locked_by", models.CharField(max_length=255)),
                ("locked_at", models.DateTimeField(auto_now_add=True)),
                ("is_locked", models.BooleanField(default=True)),
                (
                    "unlocked_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("unlocked_at", models.DateTimeField(blank=True, null=True)),
                ("unlock_reason", models.TextField(blank=True, null=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="period_locks",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "db_table": "reporting_period_locks",
                "ordering": ["-period_month"],
                "unique_together": {("org", "period_month")},
            },
        ),
    ]
