# Generated by Django 6.0.5 on 2026-05-27 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CurrencyConversionRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency_code",
                    models.CharField(
                        help_text="ISO currency code (USD, EUR, GBP, etc.)",
                        max_length=10,
                        unique=True,
                    ),
                ),
                (
                    "rate_to_inr",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Conversion rate: 1 CURRENCY = X INR",
                        max_digits=10,
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(help_text="Date when this rate became effective"),
                ),
                (
                    "source",
                    models.CharField(
                        default="RBI",
                        help_text="Source of conversion rate",
                        max_length=100,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "currency_conversion_rates",
                "ordering": ["-effective_date", "currency_code"],
            },
        ),
    ]
