# Generated by Django 6.0.5 on 2026-05-27 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("INGESTED", "Ingested"),
                            ("REVIEWED", "Reviewed"),
                            ("EDITED", "Edited"),
                            ("APPROVED", "Approved"),
                            ("FLAGGED", "Flagged"),
                            ("LOCKED", "Locked"),
                            ("UNLOCKED", "Unlocked"),
                            ("EDIT_REJECTED", "Edit Rejected"),
                            ("MANUAL_CLASSIFICATION", "Manual Classification"),
                            ("PERIOD_LOCKED", "Period Locked"),
                            ("LATE_ARRIVAL", "Late Arrival"),
                            ("FILE_INVALIDATED", "File Invalidated"),
                        ],
                        max_length=30,
                    ),
                ),
                ("performed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "field_changed",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("old_value", models.TextField(blank=True, null=True)),
                ("new_value", models.TextField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if activity deleted - log persists",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to="activities.activity",
                    ),
                ),
                (
                    "performed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null for system actions",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-performed_at"],
            },
        ),
    ]
