# Generated by Django 6.0.5 on 2026-05-27 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("audit", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="source_file",
            field=models.ForeignKey(
                blank=True,
                help_text="Null if source file deleted - log persists",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="ingestion.sourcefile",
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["activity"], name="audit_logs_activit_254eac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditlog",
            index=models.Index(
                fields=["performed_at"], name="audit_logs_perform_927549_idx"
            ),
        ),
    ]
