# Generated by Django 6.0.5 on 2026-05-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="activity_snapshot",
            field=models.JSONField(
                blank=True,
                help_text="Snapshot of activity state at time of action (category, scope, period, facility). Preserved if activity deleted.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="source_file_name",
            field=models.CharField(
                blank=True,
                help_text="Source file name snapshot. Preserved if file deleted.",
                max_length=255,
                null=True,
            ),
        ),
    ]
