# Generated by Django 6.0.5 on 2026-05-27 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scope",
                    models.IntegerField(
                        choices=[(1, "Scope 1"), (2, "Scope 2"), (3, "Scope 3")]
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("DIESEL", "Diesel"),
                            ("PETROL", "Petrol"),
                            ("NATGAS", "Natural Gas"),
                            ("LPG", "LPG"),
                            ("FUEL_OIL", "Fuel Oil"),
                            ("COAL", "Coal"),
                            ("KEROSENE", "Kerosene"),
                            ("ELECTRICITY", "Electricity"),
                            ("FLIGHT", "Flight"),
                            ("HOTEL", "Hotel"),
                            ("CAR", "Car"),
                            ("UNCLASSIFIED", "Unclassified"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "period_start",
                    models.DateField(
                        blank=True,
                        help_text="Nullable for single-date records like SAP",
                        null=True,
                    ),
                ),
                (
                    "period_end",
                    models.DateField(
                        help_text="Attribution date - month lock checks this field"
                    ),
                ),
                (
                    "emissions_kgco2e",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        help_text="Calculated emissions in kgCO2e",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("FLAGGED", "Flagged"),
                            ("APPROVED", "Approved"),
                            ("LOCKED", "Locked"),
                            ("INVALIDATED", "Invalidated"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("is_suspicious", models.BooleanField(default=False)),
                (
                    "flag_reason",
                    models.TextField(
                        blank=True,
                        help_text="Pipe-delimited if multiple flags, e.g., 'unknown_plant|negative_quantity'",
                        null=True,
                    ),
                ),
                (
                    "is_cross_month",
                    models.BooleanField(
                        default=False, help_text="Informational only, not blocking"
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "facility",
                    models.ForeignKey(
                        blank=True,
                        help_text="Null if plant code not found during ingestion",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.facility",
                    ),
                ),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="core.organization",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "activities",
                "db_table": "activities",
                "ordering": ["-period_end", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SAPDetail",
            fields=[
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="sap_detail",
                        serialize=False,
                        to="activities.activity",
                    ),
                ),
                ("plant_code", models.CharField(help_text="SAP WERKS", max_length=10)),
                (
                    "material_number",
                    models.CharField(help_text="SAP MATNR", max_length=50),
                ),
                (
                    "material_desc",
                    models.CharField(help_text="SAP MAKTX", max_length=255),
                ),
                (
                    "material_group",
                    models.CharField(
                        blank=True,
                        help_text="SAP MATKL - PRIMARY classification signal",
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "quantity_raw",
                    models.DecimalField(
                        decimal_places=3, help_text="Original value", max_digits=15
                    ),
                ),
                (
                    "unit_raw",
                    models.CharField(help_text="Original MEINS", max_length=10),
                ),
                (
                    "quantity_normalized",
                    models.DecimalField(
                        decimal_places=3,
                        help_text="Converted to canonical unit",
                        max_digits=15,
                    ),
                ),
                (
                    "unit_normalized",
                    models.CharField(help_text="L, M3, KG, KWH, etc.", max_length=10),
                ),
                (
                    "conversion_factor",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=10, null=True
                    ),
                ),
                (
                    "conversion_note",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 'GAL→L: 3.785411'",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "movement_type",
                    models.CharField(help_text="SAP BWART, e.g., '101'", max_length=10),
                ),
                (
                    "vendor_number",
                    models.CharField(
                        blank=True, help_text="SAP LIFNR", max_length=50, null=True
                    ),
                ),
                (
                    "po_number",
                    models.CharField(
                        blank=True, help_text="SAP EBELN", max_length=50, null=True
                    ),
                ),
                (
                    "classification_method",
                    models.CharField(
                        choices=[
                            ("MATKL", "Material Group (MATKL)"),
                            ("KEYWORD", "Keyword Match"),
                            ("MEINS", "Unit-based (MEINS)"),
                            ("MANUAL", "Manual Classification"),
                            ("UNCLASSIFIED", "Unclassified"),
                        ],
                        default="UNCLASSIFIED",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "db_table": "sap_details",
            },
        ),
        migrations.CreateModel(
            name="TravelDetail",
            fields=[
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="travel_detail",
                        serialize=False,
                        to="activities.activity",
                    ),
                ),
                (
                    "trip_id",
                    models.CharField(
                        help_text="Groups related rows like outbound+hotel+return",
                        max_length=50,
                    ),
                ),
                ("employee_id", models.CharField(max_length=50)),
                ("department", models.CharField(blank=True, max_length=100, null=True)),
                ("cost_center", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[
                            ("AIR", "Air"),
                            ("HOTEL", "Hotel"),
                            ("CAR", "Car"),
                            ("RAIL", "Rail"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "origin",
                    models.CharField(
                        blank=True,
                        help_text="IATA code for AIR",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        blank=True,
                        help_text="IATA code for AIR",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "distance_km",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Great circle for AIR, null for HOTEL/CAR",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "cabin_class",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ECONOMY", "Economy"),
                            ("PREMIUM", "Premium Economy"),
                            ("BUSINESS", "Business"),
                            ("FIRST", "First"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "cabin_class_raw",
                    models.CharField(
                        blank=True,
                        help_text="Original value like 'Y', 'J'",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "nights",
                    models.IntegerField(
                        blank=True, help_text="For HOTEL mode", null=True
                    ),
                ),
                ("amount_raw", models.DecimalField(decimal_places=2, max_digits=12)),
                ("currency", models.CharField(max_length=10)),
                (
                    "amount_inr",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Converted, or same if already INR",
                        max_digits=12,
                    ),
                ),
                (
                    "distance_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GREAT_CIRCLE", "Great Circle"),
                            ("SPEND_BASED", "Spend-based"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "travel_details",
            },
        ),
        migrations.CreateModel(
            name="UtilityDetail",
            fields=[
                (
                    "activity",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="utility_detail",
                        serialize=False,
                        to="activities.activity",
                    ),
                ),
                (
                    "service_number",
                    models.CharField(help_text="Meter ID", max_length=50),
                ),
                (
                    "tariff_category",
                    models.CharField(help_text="HT-1, LT-3, etc.", max_length=20),
                ),
                ("kwh_consumed", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "unit_raw",
                    models.CharField(
                        help_text="Usually kWh, flag if kVAh", max_length=10
                    ),
                ),
                (
                    "billing_amount_inr",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "grid_emission_factor",
                    models.DecimalField(
                        decimal_places=6,
                        help_text="CEA 2024 factor applied",
                        max_digits=10,
                    ),
                ),
                (
                    "emission_factor_source",
                    models.CharField(default="CEA_2024", max_length=50),
                ),
            ],
            options={
                "db_table": "utility_details",
            },
        ),
    ]
