# Generated by Django 6.0.5 on 2026-05-27 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="raw_record",
            field=models.OneToOneField(
                blank=True,
                help_text="Nullable for manual entries (future scope)",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity",
                to="ingestion.rawrecord",
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="source_file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to="ingestion.sourcefile",
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["org", "status"], name="activities_org_id_aa856b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["org", "period_end"], name="activities_org_id_81cb41_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["facility", "period_end"], name="activities_facilit_080eb2_idx"
            ),
        ),
    ]
