# Generated by Django 6.0.5 on 2026-05-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="traveldetail",
            name="amount_inr",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Converted amount in INR; NULL if currency not INR (no conversion implemented)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
