# Generated by Django 6.0.5 on 2026-05-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0003_alter_traveldetail_amount_inr"),
    ]

    operations = [
        migrations.AddField(
            model_name="traveldetail",
            name="fx_note",
            field=models.TextField(
                blank=True,
                help_text="Additional FX conversion notes (e.g., 'Used latest available rate')",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="traveldetail",
            name="fx_rate_date",
            field=models.DateField(
                blank=True, help_text="Effective date of the FX rate used", null=True
            ),
        ),
        migrations.AddField(
            model_name="traveldetail",
            name="fx_rate_used",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Exchange rate applied for conversion (e.g., 83.250000 for 1 USD = 83.25 INR)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="traveldetail",
            name="fx_source",
            field=models.CharField(
                blank=True,
                help_text="Source of FX rate (e.g., 'CurrencyConversionRate:2024-01-01')",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="traveldetail",
            name="amount_inr",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Converted amount in INR",
                max_digits=12,
                null=True,
            ),
        ),
    ]
