# Generated by Django 6.0.5 on 2026-05-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_traveldetail_fx_note_traveldetail_fx_rate_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="status",
            field=models.CharField(
                choices=[
                    ("FLAGGED", "Flagged"),
                    ("PENDING", "Pending Admin Approval"),
                    ("APPROVED", "Approved"),
                    ("LOCKED", "Locked"),
                    ("INVALIDATED", "Invalidated"),
                ],
                default="FLAGGED",
                max_length=20,
            ),
        ),
    ]
