# Generated by Django 6.0.5 on 2026-05-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0006_increase_varchar_limits"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="emissions_kgco2e",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                help_text="Calculated emissions in kgCO2e. NULL = not yet calculated. Calculation done post-ingestion via management command or background task.",
                max_digits=12,
                null=True,
            ),
        ),
    ]
