# Generated by Django 6.0.5 on 2026-05-27 02:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SourceFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("SAP", "SAP MB51"),
                            ("UTILITY", "Utility Bill"),
                            ("TRAVEL_CONCUR", "Concur Travel"),
                            ("TRAVEL_NAVAN", "Navan Travel"),
                        ],
                        max_length=20,
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                (
                    "file_hash",
                    models.CharField(
                        help_text="SHA256 hash for duplicate detection", max_length=64
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROCESSING", "Processing"),
                            ("DONE", "Done"),
                            ("FAILED", "Failed"),
                        ],
                        default="PROCESSING",
                        max_length=20,
                    ),
                ),
                ("total_rows", models.IntegerField(blank=True, null=True)),
                ("failed_rows", models.IntegerField(blank=True, default=0, null=True)),
                ("flagged_rows", models.IntegerField(blank=True, default=0, null=True)),
                (
                    "org",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_files",
                        to="core.organization",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="uploaded_files",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "source_files",
                "ordering": ["-uploaded_at"],
                "unique_together": {("org", "file_hash")},
            },
        ),
        migrations.CreateModel(
            name="RawRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_number",
                    models.IntegerField(help_text="1-indexed row number from CSV"),
                ),
                (
                    "raw_data",
                    models.JSONField(
                        help_text="Original CSV row as dict with header keys"
                    ),
                ),
                ("ingested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("EXCLUDED", "Excluded"),
                        ],
                        default="SUCCESS",
                        max_length=20,
                    ),
                ),
                ("parse_error", models.TextField(blank=True, null=True)),
                (
                    "exclude_reason",
                    models.TextField(
                        blank=True,
                        help_text="e.g., 'BWART=122 returns excluded'",
                        null=True,
                    ),
                ),
                (
                    "source_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="raw_records",
                        to="ingestion.sourcefile",
                    ),
                ),
            ],
            options={
                "db_table": "raw_records",
                "ordering": ["source_file", "row_number"],
                "indexes": [
                    models.Index(
                        fields=["source_file", "row_number"],
                        name="raw_records_source__05e171_idx",
                    )
                ],
            },
        ),
    ]
