# Generated by Django 6.0.5 on 2026-05-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcefile",
            name="approved_rows",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
