# Generated by Django 6.0.5 on 2026-05-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ingestion", "0002_sourcefile_approved_rows"),
    ]

    operations = [
        migrations.AddField(
            model_name="sourcefile",
            name="pending_rows",
            field=models.IntegerField(
                blank=True,
                default=0,
                help_text="Analyst approved, waiting for admin",
                null=True,
            ),
        ),
    ]
